#!/bin/bash

green='\033[01;32m'
restore='\033[0m'

clear

DATE_START=$(date +"%s")

read -p "Target device: " device
source build/envsetup.sh
export LC_ALL=C
lunch lineage_$device-userdebug
mka bacon

echo -e "${green}"
echo "-------------------"
echo "Build Completed in:"
echo "-------------------"
echo -e "${restore}"

DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
echo "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
echo
